version: '3.7'
services:
  applicationDB:
    container_name: applicationDB
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - node_db_data:/var/lib/postgresql/data
  node_app:
    container_name: node_app
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - applicationDB
    command: npm run dev
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
      POSTGRES_HOST: applicationDB
      POSTGRES_URL: postgres://user:pass@applicationDB:5423/db

volumes:
  node_db_data: { }